### ISSUE TITLE
固件错误

### ISSUE THREAD

**Issue by MGod-monkey** [MillerRen/ESP3D-WEBUI#2]
ESP3D版本：v3.0
3D打印机固件：Marlin v2.06
3D打印机主板：MKS Robin Nano v1.3
问题：用发行版的index.html.gz刷入之后显示固件错误
![Snipaste_2021-11-30_21-58-57](https://user-images.githubusercontent.com/62071831/144060770-9d0316ae-3ae0-49fc-9811-afb92a3fc885.png)

**Comment by MillerRen** [comment]
目前还没有适配3.0
